name: Node.js CI/CD pipleines

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.16.0'
    - name: Install dependencies
      run: npm install
    -name: Run tests
      run: npm test  